// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcXuXYo5yNazQ-0ck3r9wEXYuAADWfoj0',
    appId: '1:160848137005:web:dc8b140d1240f3b05821a4',
    messagingSenderId: '160848137005',
    projectId: 'flutter-pet-a500d',
    authDomain: 'flutter-pet-a500d.firebaseapp.com',
    storageBucket: 'flutter-pet-a500d.appspot.com',
    measurementId: 'G-7Y46RGCXFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-xv8JCzPBUewrMZabFCmaWFEqwF-c3_E',
    appId: '1:160848137005:android:9e4570408bcf58585821a4',
    messagingSenderId: '160848137005',
    projectId: 'flutter-pet-a500d',
    storageBucket: 'flutter-pet-a500d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXjt5eeD3VlWgMdFNeBAmCO6KF9l7odD4',
    appId: '1:160848137005:ios:7ebd5e8966983e315821a4',
    messagingSenderId: '160848137005',
    projectId: 'flutter-pet-a500d',
    storageBucket: 'flutter-pet-a500d.appspot.com',
    iosClientId: '160848137005-hbdre1ck97ij8tuug2ed3ti6oq7fcf51.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXjt5eeD3VlWgMdFNeBAmCO6KF9l7odD4',
    appId: '1:160848137005:ios:7ebd5e8966983e315821a4',
    messagingSenderId: '160848137005',
    projectId: 'flutter-pet-a500d',
    storageBucket: 'flutter-pet-a500d.appspot.com',
    iosClientId: '160848137005-hbdre1ck97ij8tuug2ed3ti6oq7fcf51.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPetApp',
  );
}
